"""Component for tracking unit types in the game."""

from enum import Enum

class UnitTier(Enum):
    """Enum representing the tier/experience level of a unit."""
    BASIC = "BASIC"
    VETERAN = "VETERAN"
    ELITE = "ELITE"

class UnitType(str, Enum):
    """Enum representing different types of units."""
    # Core Units - Basic Tier
    CORE_ARCHER = "CORE_ARCHER"
    CORE_BARBARIAN = "CORE_BARBARIAN"
    CORE_CAVALRY = "CORE_CAVALRY"
    CORE_DUELIST = "CORE_DUELIST"
    CORE_LONGBOWMAN = "CORE_LONGBOWMAN"
    CORE_SWORDSMAN = "CORE_SWORDSMAN"
    CORE_WIZARD = "CORE_WIZARD"
    
    # Core Units - Veteran Tier
    CORE_ARCHER_VETERAN = "CORE_ARCHER_VETERAN"
    CORE_BARBARIAN_VETERAN = "CORE_BARBARIAN_VETERAN"
    CORE_CAVALRY_VETERAN = "CORE_CAVALRY_VETERAN"
    CORE_DUELIST_VETERAN = "CORE_DUELIST_VETERAN"
    CORE_LONGBOWMAN_VETERAN = "CORE_LONGBOWMAN_VETERAN"
    CORE_SWORDSMAN_VETERAN = "CORE_SWORDSMAN_VETERAN"
    CORE_WIZARD_VETERAN = "CORE_WIZARD_VETERAN"
    
    # Core Units - Elite Tier
    CORE_ARCHER_ELITE = "CORE_ARCHER_ELITE"
    CORE_BARBARIAN_ELITE = "CORE_BARBARIAN_ELITE"
    CORE_CAVALRY_ELITE = "CORE_CAVALRY_ELITE"
    CORE_DUELIST_ELITE = "CORE_DUELIST_ELITE"
    CORE_LONGBOWMAN_ELITE = "CORE_LONGBOWMAN_ELITE"
    CORE_SWORDSMAN_ELITE = "CORE_SWORDSMAN_ELITE"
    CORE_WIZARD_ELITE = "CORE_WIZARD_ELITE"
    
    # Crusader Units - Basic Tier
    CRUSADER_BANNER_BEARER = "CRUSADER_BANNER_BEARER"
    CRUSADER_BLACK_KNIGHT = "CRUSADER_BLACK_KNIGHT"
    CRUSADER_CATAPULT = "CRUSADER_CATAPULT"
    CRUSADER_CLERIC = "CRUSADER_CLERIC"
    CRUSADER_COMMANDER = "CRUSADER_COMMANDER"
    CRUSADER_CROSSBOWMAN = "CRUSADER_CROSSBOWMAN"
    CRUSADER_DEFENDER = "CRUSADER_DEFENDER"
    CRUSADER_GOLD_KNIGHT = "CRUSADER_GOLD_KNIGHT"
    CRUSADER_GUARDIAN_ANGEL = "CRUSADER_GUARDIAN_ANGEL"
    CRUSADER_PALADIN = "CRUSADER_PALADIN"
    CRUSADER_PIKEMAN = "CRUSADER_PIKEMAN"
    CRUSADER_RED_KNIGHT = "CRUSADER_RED_KNIGHT"
    CRUSADER_SOLDIER = "CRUSADER_SOLDIER"
    
    # Crusader Units - Veteran Tier
    CRUSADER_BANNER_BEARER_VETERAN = "CRUSADER_BANNER_BEARER_VETERAN"
    CRUSADER_BLACK_KNIGHT_VETERAN = "CRUSADER_BLACK_KNIGHT_VETERAN"
    CRUSADER_CATAPULT_VETERAN = "CRUSADER_CATAPULT_VETERAN"
    CRUSADER_CLERIC_VETERAN = "CRUSADER_CLERIC_VETERAN"
    CRUSADER_COMMANDER_VETERAN = "CRUSADER_COMMANDER_VETERAN"
    CRUSADER_CROSSBOWMAN_VETERAN = "CRUSADER_CROSSBOWMAN_VETERAN"
    CRUSADER_DEFENDER_VETERAN = "CRUSADER_DEFENDER_VETERAN"
    CRUSADER_GOLD_KNIGHT_VETERAN = "CRUSADER_GOLD_KNIGHT_VETERAN"
    CRUSADER_GUARDIAN_ANGEL_VETERAN = "CRUSADER_GUARDIAN_ANGEL_VETERAN"
    CRUSADER_PALADIN_VETERAN = "CRUSADER_PALADIN_VETERAN"
    CRUSADER_PIKEMAN_VETERAN = "CRUSADER_PIKEMAN_VETERAN"
    CRUSADER_RED_KNIGHT_VETERAN = "CRUSADER_RED_KNIGHT_VETERAN"
    CRUSADER_SOLDIER_VETERAN = "CRUSADER_SOLDIER_VETERAN"
    
    # Crusader Units - Elite Tier
    CRUSADER_BANNER_BEARER_ELITE = "CRUSADER_BANNER_BEARER_ELITE"
    CRUSADER_BLACK_KNIGHT_ELITE = "CRUSADER_BLACK_KNIGHT_ELITE"
    CRUSADER_CATAPULT_ELITE = "CRUSADER_CATAPULT_ELITE"
    CRUSADER_CLERIC_ELITE = "CRUSADER_CLERIC_ELITE"
    CRUSADER_COMMANDER_ELITE = "CRUSADER_COMMANDER_ELITE"
    CRUSADER_CROSSBOWMAN_ELITE = "CRUSADER_CROSSBOWMAN_ELITE"
    CRUSADER_DEFENDER_ELITE = "CRUSADER_DEFENDER_ELITE"
    CRUSADER_GOLD_KNIGHT_ELITE = "CRUSADER_GOLD_KNIGHT_ELITE"
    CRUSADER_GUARDIAN_ANGEL_ELITE = "CRUSADER_GUARDIAN_ANGEL_ELITE"
    CRUSADER_PALADIN_ELITE = "CRUSADER_PALADIN_ELITE"
    CRUSADER_PIKEMAN_ELITE = "CRUSADER_PIKEMAN_ELITE"
    CRUSADER_RED_KNIGHT_ELITE = "CRUSADER_RED_KNIGHT_ELITE"
    CRUSADER_SOLDIER_ELITE = "CRUSADER_SOLDIER_ELITE"
    
    # Other Units - Basic Tier
    WEREBEAR = "WEREBEAR"
    ZOMBIE_BASIC_ZOMBIE = "ZOMBIE_BASIC_ZOMBIE"
    ZOMBIE_BRUTE = "ZOMBIE_BRUTE"
    ZOMBIE_GRABBER = "ZOMBIE_GRABBER"
    ZOMBIE_JUMPER = "ZOMBIE_JUMPER"
    ZOMBIE_SPITTER = "ZOMBIE_SPITTER"
    ZOMBIE_TANK = "ZOMBIE_TANK"
    
    # Other Units - Veteran Tier
    WEREBEAR_VETERAN = "WEREBEAR_VETERAN"
    ZOMBIE_BASIC_ZOMBIE_VETERAN = "ZOMBIE_BASIC_ZOMBIE_VETERAN"
    ZOMBIE_BRUTE_VETERAN = "ZOMBIE_BRUTE_VETERAN"
    ZOMBIE_GRABBER_VETERAN = "ZOMBIE_GRABBER_VETERAN"
    ZOMBIE_JUMPER_VETERAN = "ZOMBIE_JUMPER_VETERAN"
    ZOMBIE_SPITTER_VETERAN = "ZOMBIE_SPITTER_VETERAN"
    ZOMBIE_TANK_VETERAN = "ZOMBIE_TANK_VETERAN"
    
    # Other Units - Elite Tier
    WEREBEAR_ELITE = "WEREBEAR_ELITE"
    ZOMBIE_BASIC_ZOMBIE_ELITE = "ZOMBIE_BASIC_ZOMBIE_ELITE"
    ZOMBIE_BRUTE_ELITE = "ZOMBIE_BRUTE_ELITE"
    ZOMBIE_GRABBER_ELITE = "ZOMBIE_GRABBER_ELITE"
    ZOMBIE_JUMPER_ELITE = "ZOMBIE_JUMPER_ELITE"
    ZOMBIE_SPITTER_ELITE = "ZOMBIE_SPITTER_ELITE"
    ZOMBIE_TANK_ELITE = "ZOMBIE_TANK_ELITE"

    def get_base_unit_type(self) -> "UnitType":
        """Get the base unit type (Basic tier) for this unit."""
        if self.value.endswith("_VETERAN"):
            return UnitType(self.value[:-8])  # Remove "_VETERAN"
        elif self.value.endswith("_ELITE"):
            return UnitType(self.value[:-6])  # Remove "_ELITE"
        else:
            return self
    
    def get_tier(self) -> UnitTier:
        """Get the tier of this unit."""
        if self.value.endswith("_VETERAN"):
            return UnitTier.VETERAN
        elif self.value.endswith("_ELITE"):
            return UnitTier.ELITE
        else:
            return UnitTier.BASIC
    
    def get_tiered_version(self, tier: UnitTier) -> "UnitType":
        """Get the version of this unit at the specified tier."""
        base_type = self.get_base_unit_type()
        if tier == UnitTier.BASIC:
            return base_type
        elif tier == UnitTier.VETERAN:
            return UnitType(base_type.value + "_VETERAN")
        elif tier == UnitTier.ELITE:
            return UnitType(base_type.value + "_ELITE")
        else:
            raise ValueError(f"Unknown tier: {tier}")

class UnitTypeComponent:
    """Component that stores the type of a unit."""
    
    def __init__(self, type: UnitType):
        """Initialize the UnitType component.
        
        Args:
            type: The type of unit this component represents
        """
        self.type = type

