"""Component for tracking unit types in the game."""

from enum import Enum

class UnitType(str, Enum):
    """Enum representing different types of units."""
    CORE_ARCHER = "CORE_ARCHER"
    CORE_VETERAN = "CORE_VETERAN"
    CORE_CAVALRY = "CORE_CAVALRY"
    CORE_DUELIST = "CORE_DUELIST"
    CORE_LONGBOWMAN = "CORE_LONGBOWMAN"
    CORE_SWORDSMAN = "CORE_SWORDSMAN"
    CORE_WIZARD = "CORE_WIZARD"
    INFANTRY_BANNER_BEARER = "INFANTRY_BANNER_BEARER"
    CRUSADER_BLACK_KNIGHT = "CRUSADER_BLACK_KNIGHT"
    INFANTRY_CATAPULT = "INFANTRY_CATAPULT"
    CRUSADER_CLERIC = "CRUSADER_CLERIC"
    MISC_COMMANDER = "MISC_COMMANDER"
    INFANTRY_CROSSBOWMAN = "INFANTRY_CROSSBOWMAN"
    CORE_DEFENDER = "CORE_DEFENDER"
    CRUSADER_GOLD_KNIGHT = "CRUSADER_GOLD_KNIGHT"
    CRUSADER_GUARDIAN_ANGEL = "CRUSADER_GUARDIAN_ANGEL"
    CRUSADER_PALADIN = "CRUSADER_PALADIN"
    INFANTRY_PIKEMAN = "INFANTRY_PIKEMAN"
    MISC_RED_KNIGHT = "MISC_RED_KNIGHT"
    INFANTRY_SOLDIER = "INFANTRY_SOLDIER"
    ORC_BERSERKER = "ORC_BERSERKER"
    ORC_GOBLIN = "ORC_GOBLIN"
    ORC_WARG_RIDER = "ORC_WARG_RIDER"
    ORC_WARRIOR = "ORC_WARRIOR"
    ORC_WARCHIEF = "ORC_WARCHIEF"
    PIRATE_CANNON = "PIRATE_CANNON"
    PIRATE_CREW = "PIRATE_CREW"
    PIRATE_GUNNER = "PIRATE_GUNNER"
    PIRATE_CAPTAIN = "PIRATE_CAPTAIN"
    PIRATE_HARPOONER = "PIRATE_HARPOONER"
    SKELETON_ARCHER = "SKELETON_ARCHER"
    SKELETON_MAGE = "SKELETON_MAGE"
    SKELETON_SWORDSMAN = "SKELETON_SWORDSMAN"
    SKELETON_HORSEMAN = "SKELETON_HORSEMAN"
    SKELETON_ARCHER_NECROMANCER = "SKELETON_ARCHER_NECROMANCER"
    SKELETON_HORSEMAN_NECROMANCER = "SKELETON_HORSEMAN_NECROMANCER"
    SKELETON_MAGE_NECROMANCER = "SKELETON_MAGE_NECROMANCER"
    SKELETON_SWORDSMAN_NECROMANCER = "SKELETON_SWORDSMAN_NECROMANCER"
    SKELETON_LICH = "SKELETON_LICH"
    WEREBEAR = "WEREBEAR"
    ZOMBIE_BASIC_ZOMBIE = "ZOMBIE_BASIC_ZOMBIE"
    MISC_BRUTE = "MISC_BRUTE"
    ZOMBIE_FIGHTER = "ZOMBIE_FIGHTER"
    MISC_GRABBER = "MISC_GRABBER"
    ZOMBIE_JUMPER = "ZOMBIE_JUMPER"
    ZOMBIE_SPITTER = "ZOMBIE_SPITTER"
    ZOMBIE_TANK = "ZOMBIE_TANK"

class UnitTypeComponent:
    """Component that stores the type of a unit."""
    
    def __init__(self, type: UnitType):
        """Initialize the UnitType component.
        
        Args:
            type: The type of unit this component represents
        """
        self.type = type

