from components.animation import AnimationType

NO_MANS_LAND_WIDTH = 50

BATTLEFIELD_WIDTH = 1300
BATTLEFIELD_HEIGHT = 800

MINIFOLKS_SCALE = 2 + 2/3
TINY_RPG_SCALE = 2
MAGE_FIREBALL_SCALE = 1
GAME_SPEED = 1
# This messes up the balance since things don't take exact time to complete, and frames matter
# Would be better to frames per second

TARGETTING_SWITCH_BIAS = 20
# Bias against switching to another target, unless it is this much closer (pixels)

TARGETTING_GRACE_DISTANCE = 5
# Some abilities are interrupted when the target moves this far out of range

DEFAULT_AURA_PERIOD = 0.25


CORE_SWORDSMAN_HP = 300
CORE_SWORDSMAN_ATTACK_RANGE = 33
CORE_SWORDSMAN_ATTACK_DAMAGE = 50
CORE_SWORDSMAN_MOVEMENT_SPEED = 67 * GAME_SPEED
CORE_SWORDSMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 0.5 / GAME_SPEED, # Note that attack animations effect attack speed
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CORE_ARCHER_HP = CORE_SWORDSMAN_HP * 0.6
CORE_ARCHER_ATTACK_RANGE = 267
CORE_ARCHER_ATTACK_DAMAGE = 40
CORE_ARCHER_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.8
CORE_ARCHER_PROJECTILE_SPEED = 300.0 * GAME_SPEED
CORE_ARCHER_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 1.4 / GAME_SPEED,
    AnimationType.DYING: 1.2 / GAME_SPEED
}

CORE_MAGE_HP = CORE_SWORDSMAN_HP * 0.35
CORE_MAGE_ATTACK_RANGE = 400
CORE_MAGE_ATTACK_DAMAGE = 50
CORE_MAGE_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.8
CORE_MAGE_PROJECTILE_SPEED = 400.0 * GAME_SPEED
CORE_MAGE_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 3 / GAME_SPEED,
    AnimationType.DYING: 2 / GAME_SPEED
}
CORE_MAGE_FIREBALL_AOE_DURATION = 0.4
CORE_MAGE_FIREBALL_AOE_SCALE = 2 * TINY_RPG_SCALE
CORE_MAGE_IGNITE_DAMAGE = 75
CORE_MAGE_IGNITE_DURATION = 2.0

CORE_HORSEMAN_HP = CORE_SWORDSMAN_HP
CORE_HORSEMAN_ATTACK_RANGE = 53
CORE_HORSEMAN_ATTACK_DAMAGE = 60
CORE_HORSEMAN_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 2
CORE_HORSEMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.6 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 0.8 / GAME_SPEED,
    AnimationType.DYING: 1.5 / GAME_SPEED
}

CORE_DUELIST_HP = CORE_SWORDSMAN_HP
CORE_DUELIST_ATTACK_RANGE = 80
CORE_DUELIST_ATTACK_DAMAGE = 125
CORE_DUELIST_MOVEMENT_SPEED = 50 * GAME_SPEED
CORE_DUELIST_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.2 / GAME_SPEED,
    AnimationType.WALKING: 0.8 / GAME_SPEED,
    AnimationType.ABILITY1: 0.6 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CRUSADER_BLACK_KNIGHT_HP = CORE_SWORDSMAN_HP * 3.5
CRUSADER_BLACK_KNIGHT_ATTACK_RANGE = 70
CRUSADER_BLACK_KNIGHT_ATTACK_DAMAGE = 80
CRUSADER_BLACK_KNIGHT_MOVEMENT_SPEED = CORE_HORSEMAN_MOVEMENT_SPEED
CRUSADER_BLACK_KNIGHT_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.6 / GAME_SPEED,  
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 0.8 / GAME_SPEED,
    AnimationType.DYING: 1.5 / GAME_SPEED
}
# Note that this affects enemy melee and ranged damage
CRUSADER_BLACK_KNIGHT_DEBUFFED_DAMAGE_PERCENTAGE = 0.15
CRUSADER_BLACK_KNIGHT_AURA_RADIUS = 200

CRUSADER_CLERIC_HP = CORE_SWORDSMAN_HP * 0.6
CRUSADER_CLERIC_ATTACK_RANGE = 200
CRUSADER_CLERIC_HEALING = 50
CRUSADER_CLERIC_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_CLERIC_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 1 / GAME_SPEED,
    AnimationType.ABILITY1: 2 / GAME_SPEED,
    AnimationType.DYING: 0.6 / GAME_SPEED
}

# Note that this affects ally damage, excluding self
# (can be buffed by a second commander aura)
CRUSADER_COMMANDER_EMPOWERED_DAMAGE_PERCENTAGE = 0.25
CRUSADER_COMMANDER_AURA_RADIUS = 200
CRUSADER_COMMANDER_HP = CORE_SWORDSMAN_HP
CRUSADER_COMMANDER_ATTACK_RANGE = 40
CRUSADER_COMMANDER_ATTACK_DAMAGE = 40
CRUSADER_COMMANDER_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_COMMANDER_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 0.5 / GAME_SPEED, # Note that attack animations effect attack speed
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CRUSADER_DEFENDER_HP = CORE_SWORDSMAN_HP + 1
CRUSADER_DEFENDER_ARMOR_FLAT_REDUCTION = 15
CRUSADER_DEFENDER_ARMOR_PERCENT_REDUCTION = 0.1
CRUSADER_DEFENDER_ATTACK_RANGE = 33
CRUSADER_DEFENDER_ATTACK_DAMAGE = 40
CRUSADER_DEFENDER_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_DEFENDER_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 0.75 / GAME_SPEED, # Note that attack animations effect attack speed
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CRUSADER_GOLD_KNIGHT_HP = CORE_SWORDSMAN_HP * 2
CRUSADER_GOLD_KNIGHT_ATTACK_RANGE = 44
CRUSADER_GOLD_KNIGHT_ATTACK_DAMAGE = 50 # Split over 4 frames
CRUSADER_GOLD_KNIGHT_ATTACK_HEAL = 30 # Split over 4 frames
CRUSADER_GOLD_KNIGHT_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_GOLD_KNIGHT_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.2 / GAME_SPEED,
    AnimationType.WALKING: 0.8 / GAME_SPEED,
    AnimationType.ABILITY1: 0.2 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CRUSADER_LONGBOWMAN_HP = CORE_SWORDSMAN_HP * 0.6
CRUSADER_LONGBOWMAN_ATTACK_RANGE = 600
CRUSADER_LONGBOWMAN_ATTACK_DAMAGE = 250
CRUSADER_LONGBOWMAN_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.8
CRUSADER_LONGBOWMAN_PROJECTILE_SPEED = 525.0 * GAME_SPEED
CRUSADER_LONGBOWMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 3.6 / GAME_SPEED,
    AnimationType.DYING: 0.6 / GAME_SPEED
}

CRUSADER_PALADIN_HP = CORE_SWORDSMAN_HP * 3
CRUSADER_PALADIN_ATTACK_RANGE = 70
CRUSADER_PALADIN_ATTACK_DAMAGE = 50
CRUSADER_PALADIN_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 1.5
CRUSADER_PALADIN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.6 / GAME_SPEED,
    AnimationType.WALKING: 0.77 / GAME_SPEED,
    AnimationType.ABILITY2: 0.8 / GAME_SPEED, # Melee attack
    AnimationType.DYING: 1.5 / GAME_SPEED,
    AnimationType.ABILITY1: 1.2 / GAME_SPEED # Heal
}
CRUSADER_PALADIN_SKILL_COOLDOWN = 4.0
CRUSADER_PALADIN_SKILL_HEALTH_PERCENT_THRESHOLD = 0.75
CRUSADER_PALADIN_SKILL_HEAL_PERCENT = 0.5

CRUSADER_PIKEMAN_HP = CORE_SWORDSMAN_HP
CRUSADER_PIKEMAN_ATTACK_RANGE = 113
CRUSADER_PIKEMAN_ATTACK_DAMAGE = 75
CRUSADER_PIKEMAN_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_PIKEMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 1.2 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}

CRUSADER_RED_KNIGHT_HP = CORE_SWORDSMAN_HP * 1.5
CRUSADER_RED_KNIGHT_ATTACK_RANGE = 50
CRUSADER_RED_KNIGHT_ATTACK_DAMAGE = 75
CRUSADER_RED_KNIGHT_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.6
CRUSADER_RED_KNIGHT_SKILL_RANGE = 65
CRUSADER_RED_KNIGHT_SKILL_DAMAGE = 50
CRUSADER_RED_KNIGHT_SKILL_AOE_DURATION = 0.4 / GAME_SPEED
CRUSADER_RED_KNIGHT_SKILL_AOE_SCALE = TINY_RPG_SCALE
CRUSADER_RED_KNIGHT_SKILL_COOLDOWN = 8.0
CRUSADER_RED_KNIGHT_SKILL_IGNITE_DAMAGE = 100
CRUSADER_RED_KNIGHT_SKILL_IGNITED_DURATION = 4.0
CRUSADER_RED_KNIGHT_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ABILITY1: 1.467 / GAME_SPEED,
    AnimationType.ABILITY2: 0.8 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED,
}

WEREBEAR_HP = CORE_SWORDSMAN_HP * 5
WEREBEAR_ATTACK_RANGE = 50
WEREBEAR_ATTACK_DAMAGE = 50
WEREBEAR_MOVEMENT_SPEED = CORE_SWORDSMAN_MOVEMENT_SPEED * 0.4
WEREBEAR_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.2 / GAME_SPEED,
    AnimationType.WALKING: 0.7 / GAME_SPEED,
    AnimationType.ABILITY1: 0.8 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}