from components.animation import AnimationType

MINIFOLKS_SCALE = 2

SWORDSMAN_HP = 100
SWORDSMAN_ATTACK_RANGE = 12.5 * MINIFOLKS_SCALE
SWORDSMAN_ATTACK_DAMAGE = 20
SWORDSMAN_MOVEMENT_SPEED = 25.0 * MINIFOLKS_SCALE
SWORDSMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8,
    AnimationType.WALKING: 0.6,
    AnimationType.ATTACKING: 0.6, # Note that attack animations effect attack speed
    AnimationType.DYING: 0.8
}

ARCHER_HP = 60
ARCHER_ATTACK_RANGE = 100.0 * MINIFOLKS_SCALE
ARCHER_ATTACK_DAMAGE = 15
ARCHER_MOVEMENT_SPEED = 20.0 * MINIFOLKS_SCALE
ARCHER_PROJECTILE_SPEED = 150.0 * MINIFOLKS_SCALE
ARCHER_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8,
    AnimationType.WALKING: 0.6,
    AnimationType.ATTACKING: 1.8,
    AnimationType.DYING: 1.2
}

MAGE_HP = 40
MAGE_ATTACK_RANGE = 150.0 * MINIFOLKS_SCALE
MAGE_ATTACK_DAMAGE = 100
MAGE_MOVEMENT_SPEED = 30.0
MAGE_PROJECTILE_SPEED = 200.0 * MINIFOLKS_SCALE
MAGE_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8,
    AnimationType.WALKING: 0.6,
    AnimationType.ATTACKING: 3,
    AnimationType.DYING: 2
}
