from components.animation import AnimationType


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

MINIFOLKS_SCALE = 2
TINY_RPG_SCALE = 1.5
MAGE_FIREBALL_SCALE = 1
GAME_SPEED = 1

SWORDSMAN_HP = 100
SWORDSMAN_ATTACK_RANGE = 12.5 * MINIFOLKS_SCALE
SWORDSMAN_ATTACK_DAMAGE = 20
SWORDSMAN_MOVEMENT_SPEED = 25.0 * MINIFOLKS_SCALE * GAME_SPEED
SWORDSMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ATTACKING: 0.6 / GAME_SPEED, # Note that attack animations effect attack speed
    AnimationType.DYING: 0.8 / GAME_SPEED
}

ARCHER_HP = 60
ARCHER_ATTACK_RANGE = 100.0 * MINIFOLKS_SCALE
ARCHER_ATTACK_DAMAGE = 15
ARCHER_MOVEMENT_SPEED = 20.0 * MINIFOLKS_SCALE * GAME_SPEED
ARCHER_PROJECTILE_SPEED = 150.0 * MINIFOLKS_SCALE * GAME_SPEED
ARCHER_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ATTACKING: 1.8 / GAME_SPEED,
    AnimationType.DYING: 1.2 / GAME_SPEED
}

MAGE_HP = 35
MAGE_ATTACK_RANGE = 150.0 * MINIFOLKS_SCALE
MAGE_ATTACK_DAMAGE = 50
MAGE_MOVEMENT_SPEED = 15.0 * MINIFOLKS_SCALE * GAME_SPEED
MAGE_PROJECTILE_SPEED = 200.0 * MINIFOLKS_SCALE * GAME_SPEED
MAGE_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ATTACKING: 3 / GAME_SPEED,
    AnimationType.DYING: 2 / GAME_SPEED
}

HORSEMAN_HP = 200
HORSEMAN_ATTACK_RANGE = 20 * MINIFOLKS_SCALE
HORSEMAN_ATTACK_DAMAGE = 35
HORSEMAN_MOVEMENT_SPEED = 50.0 * MINIFOLKS_SCALE * GAME_SPEED
HORSEMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 0.8 / GAME_SPEED,
    AnimationType.WALKING: 0.6 / GAME_SPEED,
    AnimationType.ATTACKING: 1.2 / GAME_SPEED,
    AnimationType.DYING: 1.5 / GAME_SPEED
}

WEREBEAR_HP = 500
WEREBEAR_ATTACK_RANGE = 25 * TINY_RPG_SCALE
WEREBEAR_ATTACK_DAMAGE = 50
WEREBEAR_MOVEMENT_SPEED = 10.0 * TINY_RPG_SCALE * GAME_SPEED
WEREBEAR_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.2 / GAME_SPEED,
    AnimationType.WALKING: 0.7 / GAME_SPEED,
    AnimationType.ATTACKING: 0.8 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}

FANCY_SWORDSMAN_HP = 200
FANCY_SWORDSMAN_ATTACK_RANGE = 15 * TINY_RPG_SCALE
FANCY_SWORDSMAN_ATTACK_DAMAGE = 125
FANCY_SWORDSMAN_MOVEMENT_SPEED = 37.5 * TINY_RPG_SCALE * GAME_SPEED  # Between swordsman and horseman
FANCY_SWORDSMAN_ANIMATION_DURATIONS = {
    AnimationType.IDLE: 1.2 / GAME_SPEED,
    AnimationType.WALKING: 0.8 / GAME_SPEED,
    AnimationType.ATTACKING: 0.6 / GAME_SPEED,
    AnimationType.DYING: 0.8 / GAME_SPEED
}
