"""
Game constants configuration model.

This module defines the Pydantic model used to load and validate game constants
from JSON configuration.
"""

import os
import sys
import hashlib
import json
from pathlib import Path
from pydantic import BaseModel

def get_resource_path(relative_path: str) -> Path:
    """Get absolute path to resource, works for dev and for PyInstaller."""
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    
    return Path(base_path) / relative_path

class GameConstants(BaseModel):
    # Basic Settings
    NO_MANS_LAND_WIDTH: int
    GRID_SIZE: int
    MAJOR_GRID_INTERVAL: int  # Number of grid cells between major grid lines
    HEX_SIZE: float  # Distance from hex center to corner
    NUDGE_DISTANCE: float
    PLACEMENT_MOUSE_DISTANCE: float
    UNIT_PLACEMENT_MINIMUM_DISTANCE: float

    GRAVITY: float
    MINIFOLKS_SCALE: float
    TINY_RPG_SCALE: float
    MAGE_FIREBALL_SCALE: float
    
    # Colors
    TEAM1_COLOR: list[int]
    TEAM2_COLOR: list[int]
    MAP_BACKGROUND_COLOR: list[int]
    MAP_BATTLEFIELD_COLOR: list[int]
    MAP_BATTLEFIELD_EDGE_COLOR: list[int]
    MAP_HIGHLIGHT_COLOR: list[int]
    MAP_FOG_COLOR: list[int]
    MAP_UNFOCUSED_COLOR: list[int]

    # Target Preview Settings
    TARGET_PREVIEW_SHIFT: float
    TARGET_PREVIEW_GAP_DISTANCE: float
    TARGET_PREVIEW_DASH_LENGTH: float
    TARGET_PREVIEW_GAP_LENGTH: float
    TARGET_PREVIEW_TICK_RATE: float

    TARGETTING_SWITCH_BIAS: float
    TARGETTING_GRACE_DISTANCE: float
    DEFAULT_AURA_PERIOD: float
    FLEEING_SPEED: float
    MAX_ARMOR_DAMAGE_REDUCTION: float
    ARMOR_FLAT_DAMAGE_REDUCTION: float
    ARMOR_PERCENT_DAMAGE_REDUCTION: float
    
    # Core Units
    # Archer
    CORE_ARCHER_HP: float
    CORE_ARCHER_ATTACK_RANGE: float
    CORE_ARCHER_ATTACK_DAMAGE: float
    CORE_ARCHER_MOVEMENT_SPEED: float
    CORE_ARCHER_PROJECTILE_SPEED: float
    CORE_ARCHER_ANIMATION_IDLE_DURATION: float
    CORE_ARCHER_ANIMATION_WALKING_DURATION: float
    CORE_ARCHER_ANIMATION_ATTACK_DURATION: float
    CORE_ARCHER_ANIMATION_DYING_DURATION: float
    
    # Barbarian
    CORE_BARBARIAN_HP: float
    CORE_BARBARIAN_ATTACK_RANGE: float
    CORE_BARBARIAN_ATTACK_DAMAGE: float
    CORE_BARBARIAN_MOVEMENT_SPEED: float
    CORE_BARBARIAN_ANIMATION_IDLE_DURATION: float
    CORE_BARBARIAN_ANIMATION_WALKING_DURATION: float
    CORE_BARBARIAN_ANIMATION_ATTACK_DURATION: float
    CORE_BARBARIAN_ANIMATION_DYING_DURATION: float
    
    # Duelist
    CORE_DUELIST_HP: float
    CORE_DUELIST_ATTACK_RANGE: float
    CORE_DUELIST_ATTACK_DAMAGE: float
    CORE_DUELIST_MOVEMENT_SPEED: float
    CORE_DUELIST_ANIMATION_IDLE_DURATION: float
    CORE_DUELIST_ANIMATION_WALKING_DURATION: float
    CORE_DUELIST_ANIMATION_ATTACK_DURATION: float
    CORE_DUELIST_ANIMATION_DYING_DURATION: float
    
    # Horseman
    CORE_CAVALRY_HP: float
    CORE_CAVALRY_ATTACK_RANGE: float
    CORE_CAVALRY_ATTACK_DAMAGE: float
    CORE_CAVALRY_MOVEMENT_SPEED: float
    CORE_CAVALRY_ANIMATION_IDLE_DURATION: float
    CORE_CAVALRY_ANIMATION_WALKING_DURATION: float
    CORE_CAVALRY_ANIMATION_ATTACK_DURATION: float
    CORE_CAVALRY_ANIMATION_DYING_DURATION: float
    
    # Mage
    CORE_WIZARD_HP: float
    CORE_WIZARD_ATTACK_RANGE: float
    CORE_WIZARD_ATTACK_DAMAGE: float
    CORE_WIZARD_MOVEMENT_SPEED: float
    CORE_WIZARD_PROJECTILE_SPEED: float
    CORE_WIZARD_ANIMATION_IDLE_DURATION: float
    CORE_WIZARD_ANIMATION_WALKING_DURATION: float
    CORE_WIZARD_ANIMATION_ATTACK_DURATION: float
    CORE_WIZARD_ANIMATION_DYING_DURATION: float
    CORE_WIZARD_FIREBALL_AOE_DURATION: float
    CORE_WIZARD_FIREBALL_AOE_SCALE: float

    # Swordsman
    CORE_SWORDSMAN_HP: float
    CORE_SWORDSMAN_ATTACK_RANGE: float
    CORE_SWORDSMAN_ATTACK_DAMAGE: float
    CORE_SWORDSMAN_MOVEMENT_SPEED: float
    CORE_SWORDSMAN_ANIMATION_IDLE_DURATION: float
    CORE_SWORDSMAN_ANIMATION_WALKING_DURATION: float
    CORE_SWORDSMAN_ANIMATION_ATTACK_DURATION: float
    CORE_SWORDSMAN_ANIMATION_DYING_DURATION: float
    
    # Crusader Units

    # Banner Bearer
    CRUSADER_BANNER_BEARER_HP: float
    CRUSADER_BANNER_BEARER_ANIMATION_IDLE_DURATION: float
    CRUSADER_BANNER_BEARER_ANIMATION_WALKING_DURATION: float
    CRUSADER_BANNER_BEARER_ANIMATION_DYING_DURATION: float
    CRUSADER_BANNER_BEARER_AURA_RADIUS: float
    CRUSADER_BANNER_BEARER_AURA_DAMAGE_PERCENTAGE: float
    CRUSADER_BANNER_BEARER_AURA_MOVEMENT_SPEED: float

    # Black Knight
    CRUSADER_BLACK_KNIGHT_HP: float
    CRUSADER_BLACK_KNIGHT_ATTACK_RANGE: float
    CRUSADER_BLACK_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_BLACK_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_DYING_DURATION: float
    CRUSADER_BLACK_KNIGHT_FLEE_DURATION: float
    CRUSADER_BLACK_KNIGHT_FEAR_AOE_DURATION: float
    CRUSADER_BLACK_KNIGHT_FEAR_AOE_SCALE: float

    # Catapult
    CRUSADER_CATAPULT_HP: float
    CRUSADER_CATAPULT_MINIMUM_RANGE: float
    CRUSADER_CATAPULT_MAXIMUM_RANGE: float
    CRUSADER_CATAPULT_DAMAGE: float
    CRUSADER_CATAPULT_AOE_DURATION: float
    CRUSADER_CATAPULT_AOE_SCALE: float
    CRUSADER_CATAPULT_COOLDOWN: float
    CRUSADER_CATAPULT_ANIMATION_IDLE_DURATION: float
    CRUSADER_CATAPULT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_CATAPULT_ANIMATION_DYING_DURATION: float

    # Cleric
    CRUSADER_CLERIC_HP: float
    CRUSADER_CLERIC_ATTACK_RANGE: float
    CRUSADER_CLERIC_HEALING: float
    CRUSADER_CLERIC_MOVEMENT_SPEED: float
    CRUSADER_CLERIC_ANIMATION_IDLE_DURATION: float
    CRUSADER_CLERIC_ANIMATION_WALKING_DURATION: float
    CRUSADER_CLERIC_ANIMATION_ATTACK_DURATION: float
    CRUSADER_CLERIC_ANIMATION_DYING_DURATION: float

    # Commander
    CRUSADER_COMMANDER_EMPOWERED_DAMAGE_PERCENTAGE: float
    CRUSADER_COMMANDER_AURA_RADIUS: float
    CRUSADER_COMMANDER_HP: float
    CRUSADER_COMMANDER_ATTACK_RANGE: float
    CRUSADER_COMMANDER_ATTACK_DAMAGE: float
    CRUSADER_COMMANDER_MOVEMENT_SPEED: float
    CRUSADER_COMMANDER_ANIMATION_IDLE_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_WALKING_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_ATTACK_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_DYING_DURATION: float
    
    # Crossbowman
    CRUSADER_CROSSBOWMAN_HP: float
    CRUSADER_CROSSBOWMAN_ATTACK_RANGE: float
    CRUSADER_CROSSBOWMAN_ATTACK_DAMAGE: float
    CRUSADER_CROSSBOWMAN_MOVEMENT_SPEED: float
    CRUSADER_CROSSBOWMAN_PROJECTILE_SPEED: float
    CRUSADER_CROSSBOWMAN_ANIMATION_IDLE_DURATION: float
    CRUSADER_CROSSBOWMAN_ANIMATION_WALKING_DURATION: float
    CRUSADER_CROSSBOWMAN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_CROSSBOWMAN_ANIMATION_RELOAD_DURATION: float
    CRUSADER_CROSSBOWMAN_ANIMATION_DYING_DURATION: float
    CRUSADER_CROSSBOWMAN_MAX_AMMO: int
    CRUSADER_CROSSBOWMAN_STARTING_AMMO: int

    # Defender
    CRUSADER_DEFENDER_HP: float
    CRUSADER_DEFENDER_ATTACK_RANGE: float
    CRUSADER_DEFENDER_ATTACK_DAMAGE: float
    CRUSADER_DEFENDER_MOVEMENT_SPEED: float
    CRUSADER_DEFENDER_ANIMATION_IDLE_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_WALKING_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_ATTACK_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_DYING_DURATION: float
    
    # Gold Knight
    CRUSADER_GOLD_KNIGHT_HP: float
    CRUSADER_GOLD_KNIGHT_ATTACK_RANGE: float
    CRUSADER_GOLD_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_GOLD_KNIGHT_ATTACK_HEAL: float
    CRUSADER_GOLD_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_DYING_DURATION: float

    # Guardian Angel
    CRUSADER_GUARDIAN_ANGEL_HP: float
    CRUSADER_GUARDIAN_ANGEL_HEALING: float
    CRUSADER_GUARDIAN_ANGEL_MOVEMENT_SPEED: float
    CRUSADER_GUARDIAN_ANGEL_HEAL_COOLDOWN: float
    CRUSADER_GUARDIAN_ANGEL_ANIMATION_FLYING_DURATION: float
    CRUSADER_GUARDIAN_ANGEL_ANIMATION_DYING_DURATION: float
    CRUSADER_GUARDIAN_ANGEL_ATTACHMENT_RANGE: float
    
    # Longbowman
    CRUSADER_LONGBOWMAN_HP: float
    CRUSADER_LONGBOWMAN_ATTACK_RANGE: float
    CRUSADER_LONGBOWMAN_ATTACK_DAMAGE: float
    CRUSADER_LONGBOWMAN_MOVEMENT_SPEED: float
    CRUSADER_LONGBOWMAN_PROJECTILE_SPEED: float
    CRUSADER_LONGBOWMAN_ANIMATION_IDLE_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_WALKING_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_DYING_DURATION: float
    
    # Paladin
    CRUSADER_PALADIN_HP: float
    CRUSADER_PALADIN_ATTACK_RANGE: float
    CRUSADER_PALADIN_ATTACK_DAMAGE: float
    CRUSADER_PALADIN_MOVEMENT_SPEED: float
    CRUSADER_PALADIN_ANIMATION_IDLE_DURATION: float
    CRUSADER_PALADIN_ANIMATION_WALKING_DURATION: float
    CRUSADER_PALADIN_ANIMATION_SKILL_DURATION: float
    CRUSADER_PALADIN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_PALADIN_ANIMATION_DYING_DURATION: float
    CRUSADER_PALADIN_SKILL_COOLDOWN: float
    CRUSADER_PALADIN_SKILL_HEALTH_PERCENT_THRESHOLD: float
    CRUSADER_PALADIN_SKILL_HEAL_PERCENT: float
    
    # Pikeman
    CRUSADER_PIKEMAN_HP: float
    CRUSADER_PIKEMAN_ATTACK_RANGE: float
    CRUSADER_PIKEMAN_ATTACK_DAMAGE: float
    CRUSADER_PIKEMAN_MOVEMENT_SPEED: float
    CRUSADER_PIKEMAN_ANIMATION_IDLE_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_WALKING_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_STANCE_CHANGE_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_DYING_DURATION: float
    
    # Red Knight
    CRUSADER_RED_KNIGHT_HP: float
    CRUSADER_RED_KNIGHT_ATTACK_RANGE: float
    CRUSADER_RED_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_RED_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_RED_KNIGHT_SKILL_RANGE: float
    CRUSADER_RED_KNIGHT_SKILL_DAMAGE: float
    CRUSADER_RED_KNIGHT_SKILL_AOE_DURATION: float
    CRUSADER_RED_KNIGHT_SKILL_AOE_SCALE: float
    CRUSADER_RED_KNIGHT_SKILL_COOLDOWN: float
    CRUSADER_RED_KNIGHT_SKILL_IGNITE_DAMAGE: float
    CRUSADER_RED_KNIGHT_SKILL_IGNITED_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_SKILL_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_DYING_DURATION: float
    
    # Soldier
    CRUSADER_SOLDIER_HP: float
    CRUSADER_SOLDIER_MELEE_RANGE: float
    CRUSADER_SOLDIER_MELEE_DAMAGE: float
    CRUSADER_SOLDIER_RANGED_RANGE: float
    CRUSADER_SOLDIER_RANGED_DAMAGE: float
    CRUSADER_SOLDIER_MOVEMENT_SPEED: float
    CRUSADER_SOLDIER_SWITCH_STANCE_RANGE: float
    CRUSADER_SOLDIER_ANIMATION_IDLE_DURATION: float
    CRUSADER_SOLDIER_ANIMATION_WALKING_DURATION: float
    CRUSADER_SOLDIER_ANIMATION_MELEE_ATTACK_DURATION: float
    CRUSADER_SOLDIER_ANIMATION_RANGED_ATTACK_DURATION: float
    CRUSADER_SOLDIER_ANIMATION_SWITCH_STANCE_DURATION: float
    CRUSADER_SOLDIER_ANIMATION_DYING_DURATION: float
    
    # Werebear
    WEREBEAR_HP: float
    WEREBEAR_ATTACK_RANGE: float
    WEREBEAR_ATTACK_DAMAGE: float
    WEREBEAR_MOVEMENT_SPEED: float
    WEREBEAR_ANIMATION_IDLE_DURATION: float
    WEREBEAR_ANIMATION_WALKING_DURATION: float
    WEREBEAR_ANIMATION_ATTACK_DURATION: float
    WEREBEAR_ANIMATION_DYING_DURATION: float


    # Zombie Units
    ZOMBIE_INFECTION_DURATION: float

    # Basic Zombie
    ZOMBIE_BASIC_ZOMBIE_HP: float
    ZOMBIE_BASIC_ZOMBIE_ATTACK_RANGE: float
    ZOMBIE_BASIC_ZOMBIE_ATTACK_DAMAGE: float
    ZOMBIE_BASIC_ZOMBIE_MOVEMENT_SPEED: float
    ZOMBIE_BASIC_ZOMBIE_ANIMATION_IDLE_DURATION: float
    ZOMBIE_BASIC_ZOMBIE_ANIMATION_WALKING_DURATION: float
    ZOMBIE_BASIC_ZOMBIE_ANIMATION_ATTACK_DURATION: float
    ZOMBIE_BASIC_ZOMBIE_ANIMATION_DYING_DURATION: float

    # Jumper
    ZOMBIE_JUMPER_HP: float
    ZOMBIE_JUMPER_ATTACK_RANGE: float
    ZOMBIE_JUMPER_ATTACK_DAMAGE: float
    ZOMBIE_JUMPER_MINIMUM_JUMP_RANGE: float
    ZOMBIE_JUMPER_MAXIMUM_JUMP_RANGE: float
    ZOMBIE_JUMPER_MAXIMUM_JUMP_ANGLE: float
    ZOMBIE_JUMPER_JUMP_DAMAGE: float
    ZOMBIE_JUMPER_JUMP_COOLDOWN: float
    ZOMBIE_JUMPER_MOVEMENT_SPEED: float
    ZOMBIE_JUMPER_ANIMATION_IDLE_DURATION: float
    ZOMBIE_JUMPER_ANIMATION_WALKING_DURATION: float
    ZOMBIE_JUMPER_ANIMATION_ATTACK_DURATION: float
    ZOMBIE_JUMPER_ANIMATION_DYING_DURATION: float
    ZOMBIE_JUMPER_ANIMATION_JUMPING_DURATION: float
    ZOMBIE_JUMPER_ANIMATION_AIRBORNE_DURATION: float

    # Spitter
    ZOMBIE_SPITTER_HP: float
    ZOMBIE_SPITTER_ATTACK_RANGE: float
    ZOMBIE_SPITTER_ATTACK_DAMAGE: float
    ZOMBIE_SPITTER_MOVEMENT_SPEED: float
    ZOMBIE_SPITTER_PROJECTILE_SPEED: float
    ZOMBIE_SPITTER_ANIMATION_IDLE_DURATION: float
    ZOMBIE_SPITTER_ANIMATION_WALKING_DURATION: float
    ZOMBIE_SPITTER_ANIMATION_ATTACK_DURATION: float
    ZOMBIE_SPITTER_ANIMATION_DYING_DURATION: float

    # Tank
    ZOMBIE_TANK_HP: float
    ZOMBIE_TANK_ATTACK_RANGE: float
    ZOMBIE_TANK_ATTACK_DAMAGE: float
    ZOMBIE_TANK_MOVEMENT_SPEED: float
    ZOMBIE_TANK_ANIMATION_IDLE_DURATION: float
    ZOMBIE_TANK_ANIMATION_WALKING_DURATION: float
    ZOMBIE_TANK_ANIMATION_ATTACK_DURATION: float
    ZOMBIE_TANK_ANIMATION_DYING_DURATION: float

    # Brute
    ZOMBIE_BRUTE_HP: float
    ZOMBIE_BRUTE_ATTACK_RANGE: float
    ZOMBIE_BRUTE_ATTACK_DAMAGE: float
    ZOMBIE_BRUTE_MOVEMENT_SPEED: float
    ZOMBIE_BRUTE_ANIMATION_IDLE_DURATION: float
    ZOMBIE_BRUTE_ANIMATION_WALKING_DURATION: float
    ZOMBIE_BRUTE_ANIMATION_ATTACK_DURATION: float
    ZOMBIE_BRUTE_ANIMATION_DYING_DURATION: float
    ZOMBIE_BRUTE_ZOMBIE_DROP_RANGE: float

    # Camera animation constants
    CAMERA_ANIMATION_DURATION_SCALE: float  # A: scales overall animation duration
    CAMERA_ANIMATION_DURATION_EXPONENT: float  # B: sub-linear exponent in (0, 1)
    CAMERA_ANIMATION_ZOOM_VELOCITY_SCALE: float  # gamma: how strongly velocity affects zoom
    CAMERA_ANIMATION_ZOOM_DURATION_SCALE: float  # scales duration of zoom animations
    CAMERA_ANIMATION_SOFTMIN_INTENSITY: float  # intensity parameter for softmin function
    CAMERA_ANIMATION_EASE_POWER: float  # power parameter for ease out and in function

    class Config:
        frozen = False

gc = None

def get_game_constants_hash() -> str:
    """Calculate a hash of the current game constants."""
    reload_game_constants()
    # Convert the model to a dictionary and then to a JSON string
    gc_dict = gc.model_dump()
    gc_json = json.dumps(gc_dict, sort_keys=True)
    
    # Calculate the hash
    return hashlib.md5(gc_json.encode()).hexdigest()

def reload_game_constants() -> None:
    """Reload the game constants from the JSON file."""
    global gc
    constants_path = get_resource_path("data/game_constants.json")
    with open(constants_path, "r") as file:
        new_gc = GameConstants.model_validate_json(file.read())
        if gc is None:
            gc = new_gc
        else:
            for field in gc.model_fields:
                setattr(gc, field, getattr(new_gc, field))

reload_game_constants()
