"""
Game constants configuration model.

This module defines the Pydantic model used to load and validate game constants
from JSON configuration.
"""

from pathlib import Path
from pydantic import BaseModel

class GameConstants(BaseModel):
    # Basic Settings
    NO_MANS_LAND_WIDTH: int
    BATTLEFIELD_WIDTH: int
    BATTLEFIELD_HEIGHT: int
    
    MINIFOLKS_SCALE: float
    TINY_RPG_SCALE: float
    MAGE_FIREBALL_SCALE: float
    
    TARGETTING_SWITCH_BIAS: float
    TARGETTING_GRACE_DISTANCE: float
    DEFAULT_AURA_PERIOD: float
    FLEEING_SPEED: float
    
    # Core Units
    # Archer
    CORE_ARCHER_HP: float
    CORE_ARCHER_ATTACK_RANGE: float
    CORE_ARCHER_ATTACK_DAMAGE: float
    CORE_ARCHER_MOVEMENT_SPEED: float
    CORE_ARCHER_PROJECTILE_SPEED: float
    CORE_ARCHER_ANIMATION_IDLE_DURATION: float
    CORE_ARCHER_ANIMATION_WALKING_DURATION: float
    CORE_ARCHER_ANIMATION_ATTACK_DURATION: float
    CORE_ARCHER_ANIMATION_DYING_DURATION: float
    
    # Duelist
    CORE_DUELIST_HP: float
    CORE_DUELIST_ATTACK_RANGE: float
    CORE_DUELIST_ATTACK_DAMAGE: float
    CORE_DUELIST_MOVEMENT_SPEED: float
    CORE_DUELIST_ANIMATION_IDLE_DURATION: float
    CORE_DUELIST_ANIMATION_WALKING_DURATION: float
    CORE_DUELIST_ANIMATION_ATTACK_DURATION: float
    CORE_DUELIST_ANIMATION_DYING_DURATION: float
    
    # Horseman
    CORE_HORSEMAN_HP: float
    CORE_HORSEMAN_ATTACK_RANGE: float
    CORE_HORSEMAN_ATTACK_DAMAGE: float
    CORE_HORSEMAN_MOVEMENT_SPEED: float
    CORE_HORSEMAN_ANIMATION_IDLE_DURATION: float
    CORE_HORSEMAN_ANIMATION_WALKING_DURATION: float
    CORE_HORSEMAN_ANIMATION_ATTACK_DURATION: float
    CORE_HORSEMAN_ANIMATION_DYING_DURATION: float
    
    # Mage
    CORE_MAGE_HP: float
    CORE_MAGE_ATTACK_RANGE: float
    CORE_MAGE_ATTACK_DAMAGE: float
    CORE_MAGE_MOVEMENT_SPEED: float
    CORE_MAGE_PROJECTILE_SPEED: float
    CORE_MAGE_ANIMATION_IDLE_DURATION: float
    CORE_MAGE_ANIMATION_WALKING_DURATION: float
    CORE_MAGE_ANIMATION_ATTACK_DURATION: float
    CORE_MAGE_ANIMATION_DYING_DURATION: float
    CORE_MAGE_FIREBALL_AOE_DURATION: float
    CORE_MAGE_FIREBALL_AOE_SCALE: float
    CORE_MAGE_IGNITE_DAMAGE: float
    CORE_MAGE_IGNITE_DURATION: float

    # Swordsman
    CORE_SWORDSMAN_HP: float
    CORE_SWORDSMAN_ATTACK_RANGE: float
    CORE_SWORDSMAN_ATTACK_DAMAGE: float
    CORE_SWORDSMAN_MOVEMENT_SPEED: float
    CORE_SWORDSMAN_ANIMATION_IDLE_DURATION: float
    CORE_SWORDSMAN_ANIMATION_WALKING_DURATION: float
    CORE_SWORDSMAN_ANIMATION_ATTACK_DURATION: float
    CORE_SWORDSMAN_ANIMATION_DYING_DURATION: float
    
    # Crusader Units
    # Black Knight
    CRUSADER_BLACK_KNIGHT_HP: float
    CRUSADER_BLACK_KNIGHT_ATTACK_RANGE: float
    CRUSADER_BLACK_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_BLACK_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_BLACK_KNIGHT_ANIMATION_DYING_DURATION: float
    CRUSADER_BLACK_KNIGHT_AURA_RADIUS: float
    CRUSADER_BLACK_KNIGHT_AURA_DURATION: float
    CRUSADER_BLACK_KNIGHT_AURA_FLEE_DURATION: float
    
    # Cleric
    CRUSADER_CLERIC_HP: float
    CRUSADER_CLERIC_ATTACK_RANGE: float
    CRUSADER_CLERIC_HEALING: float
    CRUSADER_CLERIC_MOVEMENT_SPEED: float
    CRUSADER_CLERIC_ANIMATION_IDLE_DURATION: float
    CRUSADER_CLERIC_ANIMATION_WALKING_DURATION: float
    CRUSADER_CLERIC_ANIMATION_ATTACK_DURATION: float
    CRUSADER_CLERIC_ANIMATION_DYING_DURATION: float
    
    # Commander
    CRUSADER_COMMANDER_EMPOWERED_DAMAGE_PERCENTAGE: float
    CRUSADER_COMMANDER_AURA_RADIUS: float
    CRUSADER_COMMANDER_HP: float
    CRUSADER_COMMANDER_ATTACK_RANGE: float
    CRUSADER_COMMANDER_ATTACK_DAMAGE: float
    CRUSADER_COMMANDER_MOVEMENT_SPEED: float
    CRUSADER_COMMANDER_ANIMATION_IDLE_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_WALKING_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_ATTACK_DURATION: float
    CRUSADER_COMMANDER_ANIMATION_DYING_DURATION: float
    
    # Defender
    CRUSADER_DEFENDER_HP: float
    CRUSADER_DEFENDER_ARMOR_FLAT_REDUCTION: float
    CRUSADER_DEFENDER_ARMOR_PERCENT_REDUCTION: float
    CRUSADER_DEFENDER_ATTACK_RANGE: float
    CRUSADER_DEFENDER_ATTACK_DAMAGE: float
    CRUSADER_DEFENDER_MOVEMENT_SPEED: float
    CRUSADER_DEFENDER_ANIMATION_IDLE_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_WALKING_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_ATTACK_DURATION: float
    CRUSADER_DEFENDER_ANIMATION_DYING_DURATION: float
    
    # Gold Knight
    CRUSADER_GOLD_KNIGHT_HP: float
    CRUSADER_GOLD_KNIGHT_ATTACK_RANGE: float
    CRUSADER_GOLD_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_GOLD_KNIGHT_ATTACK_HEAL: float
    CRUSADER_GOLD_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_GOLD_KNIGHT_ANIMATION_DYING_DURATION: float
    
    # Longbowman
    CRUSADER_LONGBOWMAN_HP: float
    CRUSADER_LONGBOWMAN_ATTACK_RANGE: float
    CRUSADER_LONGBOWMAN_ATTACK_DAMAGE: float
    CRUSADER_LONGBOWMAN_MOVEMENT_SPEED: float
    CRUSADER_LONGBOWMAN_PROJECTILE_SPEED: float
    CRUSADER_LONGBOWMAN_ANIMATION_IDLE_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_WALKING_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_LONGBOWMAN_ANIMATION_DYING_DURATION: float
    
    # Paladin
    CRUSADER_PALADIN_HP: float
    CRUSADER_PALADIN_ATTACK_RANGE: float
    CRUSADER_PALADIN_ATTACK_DAMAGE: float
    CRUSADER_PALADIN_MOVEMENT_SPEED: float
    CRUSADER_PALADIN_ANIMATION_IDLE_DURATION: float
    CRUSADER_PALADIN_ANIMATION_WALKING_DURATION: float
    CRUSADER_PALADIN_ANIMATION_SKILL_DURATION: float
    CRUSADER_PALADIN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_PALADIN_ANIMATION_DYING_DURATION: float
    CRUSADER_PALADIN_SKILL_COOLDOWN: float
    CRUSADER_PALADIN_SKILL_HEALTH_PERCENT_THRESHOLD: float
    CRUSADER_PALADIN_SKILL_HEAL_PERCENT: float
    
    # Pikeman
    CRUSADER_PIKEMAN_HP: float
    CRUSADER_PIKEMAN_ATTACK_RANGE: float
    CRUSADER_PIKEMAN_ATTACK_DAMAGE: float
    CRUSADER_PIKEMAN_MOVEMENT_SPEED: float
    CRUSADER_PIKEMAN_ANIMATION_IDLE_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_WALKING_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_ATTACK_DURATION: float
    CRUSADER_PIKEMAN_ANIMATION_DYING_DURATION: float
    
    # Red Knight
    CRUSADER_RED_KNIGHT_HP: float
    CRUSADER_RED_KNIGHT_ATTACK_RANGE: float
    CRUSADER_RED_KNIGHT_ATTACK_DAMAGE: float
    CRUSADER_RED_KNIGHT_MOVEMENT_SPEED: float
    CRUSADER_RED_KNIGHT_SKILL_RANGE: float
    CRUSADER_RED_KNIGHT_SKILL_DAMAGE: float
    CRUSADER_RED_KNIGHT_SKILL_AOE_DURATION: float
    CRUSADER_RED_KNIGHT_SKILL_AOE_SCALE: float
    CRUSADER_RED_KNIGHT_SKILL_COOLDOWN: float
    CRUSADER_RED_KNIGHT_SKILL_IGNITE_DAMAGE: float
    CRUSADER_RED_KNIGHT_SKILL_IGNITED_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_IDLE_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_WALKING_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_SKILL_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_ATTACK_DURATION: float
    CRUSADER_RED_KNIGHT_ANIMATION_DYING_DURATION: float
    
    # Werebear
    WEREBEAR_HP: float
    WEREBEAR_ATTACK_RANGE: float
    WEREBEAR_ATTACK_DAMAGE: float
    WEREBEAR_MOVEMENT_SPEED: float
    WEREBEAR_ANIMATION_IDLE_DURATION: float
    WEREBEAR_ANIMATION_WALKING_DURATION: float
    WEREBEAR_ANIMATION_ATTACK_DURATION: float
    WEREBEAR_ANIMATION_DYING_DURATION: float


gc = None

def reload_game_constants() -> None:
    """Reload the game constants from the JSON file."""
    global gc
    with open(Path(__file__).parent.parent / "data" / "game_constants.json", "r") as file:
        gc = GameConstants.model_validate_json(file.read())

reload_game_constants()
