from components.unit_type import UnitType
from entities.items import ItemType
from components.spell_type import SpellType
from typing import Dict
from game_constants import gc

unit_values: Dict[UnitType, int] = {
    UnitType.CORE_ARCHER: gc.CORE_ARCHER_POINTS,
    UnitType.CORE_VETERAN: gc.CORE_VETERAN_POINTS,
    UnitType.CORE_CAVALRY: gc.CORE_CAVALRY_POINTS,
    UnitType.CORE_DUELIST: gc.CORE_DUELIST_POINTS,
    UnitType.CORE_LONGBOWMAN: gc.CORE_LONGBOWMAN_POINTS,
    UnitType.CORE_SWORDSMAN: gc.CORE_SWORDSMAN_POINTS,
    UnitType.CORE_WIZARD: gc.CORE_WIZARD_POINTS,
    UnitType.INFANTRY_BANNER_BEARER: gc.INFANTRY_BANNER_BEARER_POINTS,
    UnitType.CRUSADER_BLACK_KNIGHT: gc.CRUSADER_BLACK_KNIGHT_POINTS,
    UnitType.INFANTRY_CATAPULT: gc.INFANTRY_CATAPULT_POINTS,
    UnitType.CRUSADER_CLERIC: gc.CRUSADER_CLERIC_POINTS,
    UnitType.MISC_COMMANDER: gc.MISC_COMMANDER_POINTS,
    UnitType.INFANTRY_CROSSBOWMAN: gc.INFANTRY_CROSSBOWMAN_POINTS,
    UnitType.CORE_DEFENDER: gc.CORE_DEFENDER_POINTS,
    UnitType.CRUSADER_GOLD_KNIGHT: gc.CRUSADER_GOLD_KNIGHT_POINTS,
    UnitType.CRUSADER_GUARDIAN_ANGEL: gc.CRUSADER_GUARDIAN_ANGEL_POINTS,
    UnitType.CRUSADER_PALADIN: gc.CRUSADER_PALADIN_POINTS,
    UnitType.INFANTRY_PIKEMAN: gc.INFANTRY_PIKEMAN_POINTS,
    UnitType.MISC_RED_KNIGHT: gc.MISC_RED_KNIGHT_POINTS,
    UnitType.INFANTRY_SOLDIER: gc.INFANTRY_SOLDIER_POINTS,
    UnitType.ORC_BERSERKER: gc.ORC_BERSERKER_POINTS,
    UnitType.ORC_WARRIOR: gc.ORC_WARRIOR_POINTS,
    UnitType.ORC_WARCHIEF: gc.ORC_WARCHIEF_POINTS,
    UnitType.ORC_GOBLIN: gc.ORC_GOBLIN_POINTS,
    UnitType.ORC_WARG_RIDER: gc.ORC_WARG_RIDER_POINTS,
    UnitType.PIRATE_CREW: gc.PIRATE_CREW_POINTS,
    UnitType.PIRATE_GUNNER: gc.PIRATE_GUNNER_POINTS,
    UnitType.PIRATE_CAPTAIN: gc.PIRATE_CAPTAIN_POINTS,
    UnitType.PIRATE_CANNON: gc.PIRATE_CANNON_POINTS,
    UnitType.PIRATE_HARPOONER: gc.PIRATE_HARPOONER_POINTS,
    UnitType.SKELETON_ARCHER: gc.SKELETON_ARCHER_POINTS,
    UnitType.SKELETON_LICH: gc.SKELETON_LICH_POINTS,
    UnitType.SKELETON_MAGE: gc.SKELETON_MAGE_POINTS,
    UnitType.SKELETON_SWORDSMAN: gc.SKELETON_SWORDSMAN_POINTS,
    UnitType.SKELETON_HORSEMAN: gc.SKELETON_HORSEMAN_POINTS,
    UnitType.SKELETON_ARCHER_NECROMANCER: gc.SKELETON_ARCHER_NECROMANCER_POINTS,
    UnitType.SKELETON_HORSEMAN_NECROMANCER: gc.SKELETON_HORSEMAN_NECROMANCER_POINTS,
    UnitType.SKELETON_MAGE_NECROMANCER: gc.SKELETON_MAGE_NECROMANCER_POINTS,
    UnitType.SKELETON_SWORDSMAN_NECROMANCER: gc.SKELETON_SWORDSMAN_NECROMANCER_POINTS,
    UnitType.WEREBEAR: gc.WEREBEAR_POINTS,
    UnitType.ZOMBIE_BASIC_ZOMBIE: gc.ZOMBIE_BASIC_ZOMBIE_POINTS,
    UnitType.MISC_BRUTE: gc.MISC_BRUTE_POINTS,
    UnitType.ZOMBIE_FIGHTER: gc.ZOMBIE_FIGHTER_POINTS,
    UnitType.MISC_GRABBER: gc.MISC_GRABBER_POINTS,
    UnitType.ZOMBIE_JUMPER: gc.ZOMBIE_JUMPER_POINTS,
    UnitType.ZOMBIE_SPITTER: gc.ZOMBIE_SPITTER_POINTS,
    UnitType.ZOMBIE_TANK: gc.ZOMBIE_TANK_POINTS,
}

# Item point values
item_values: Dict[ItemType, int] = {
    ItemType.EXTRA_HEALTH: gc.ITEM_EXTRA_HEALTH_POINTS,
    ItemType.EXPLODE_ON_DEATH: gc.ITEM_EXPLODE_ON_DEATH_POINTS,
    ItemType.UPGRADE_ARMOR: gc.ITEM_UPGRADE_ARMOR_POINTS,
    ItemType.DAMAGE_AURA: gc.ITEM_DAMAGE_AURA_POINTS,
}

# Spell point values
spell_values: Dict[SpellType, int] = {
    SpellType.SUMMON_SKELETON_SWORDSMEN: gc.SPELL_SUMMON_SKELETON_SWORDSMEN_POINTS,
}