name: Build and Package Game

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py
      working-directory: src

    - name: Prepare distribution folder
      run: |
        mkdir dist\BattleSwap
        copy src\dist\main.exe dist\BattleSwap\BattleSwap.exe
        xcopy assets dist\BattleSwap\assets /E /I
        copy theme.json dist\BattleSwap\theme.json

    - name: Create ZIP archive
      run: |
        powershell Compress-Archive -Path dist\BattleSwap\* -DestinationPath dist\BattleSwap-Windows.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BattleSwap-Windows
        path: dist/BattleSwap-Windows.zip
